/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 27/03/2022 17:24:16
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     72000000
#define MX_SYSCLKFreq_VALUE                     72000000
#define MX_HCLKFreq_Value                       72000000
#define MX_FCLKCortexFreq_Value                 72000000
#define MX_CortexFreq_Value                     72000000
#define MX_AHBFreq_Value                        72000000
#define MX_APB1Freq_Value                       36000000
#define MX_APB2Freq_Value                       72000000
#define MX_APB1TimFreq_Value                    72000000
#define MX_APB2TimFreq_Value                    72000000
#define MX_48MHZClocksFreq_Value                36000000
#define MX_EthernetFreq_Value                   72000000
#define MX_I2SClocksFreq_Value                  48000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    72000000

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC7 */
#define MX_USART6_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_RX_Pin                        PC7
#define MX_USART6_RX_GPIOx                      GPIOC
#define MX_USART6_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART6_RX_GPIO_AF                    GPIO_AF8_USART6

/* Pin PC6 */
#define MX_USART6_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_TX_Pin                        PC6
#define MX_USART6_TX_GPIOx                      GPIOC
#define MX_USART6_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART6_TX_GPIO_AF                    GPIO_AF8_USART6

/* DMA Configuration */

/* DMA USART6_RX */
#define MX_USART6_RX_DMA_DMA_Handle             
#define MX_USART6_RX_DMA_Instance               DMA2_Stream1
#define MX_USART6_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART6_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART6_RX_DMA_Channel                DMA_CHANNEL_5
#define MX_USART6_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART6_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART6_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART6_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART6_RX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_USART6_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART6_RX_DMA_IpInstance             

/* NVIC Configuration */

/* NVIC USART6_IRQn */
#define MX_USART6_IRQn_interruptPremptionPriority 0
#define MX_USART6_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART6_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_GPIO_PuPd                        GPIO_PULLUP
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

